### ISSUE TITLE
Add a new ControlParameter for token arrivals over a calendar period

### ISSUE THREAD

**Issue by jhorgan** [BusinessProcessSimulation/BPSim#10]
We have needed this functionality in a customer project.
Objective: set a number of arrivals to occur in a given time period. The current Trigger Count and Inter trigger time do not do this.
Solution: a new parameter that specifies the number of tokens to arrive over the duration of a calendar.

We added a vendor extension to achieve this which spreads the quantity of tokens randomly over the calendar duration
![image](https://cloud.githubusercontent.com/assets/17126137/16562861/dcf15714-41f6-11e6-988f-f7dcea425ceb.png)

Our suggested implementation for BPSim is:
![image](https://cloud.githubusercontent.com/assets/17126137/16563033/c1cf58e0-41f7-11e6-8ff2-6b1f8c5536a4.png)

**Comment by ldugan** [comment]
I need this as well for a client.  Have had to show trigger as a continuous stream instead of counts occurring in specific time periods, which leads to an I unintended end (and inaccurate) smoothness to the triggers.  In particular, I'm looking to model call centers on a very robust way, and see this as part of that problem.

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we have decided to add a clarification to the validFor attribute of a ParameterValue. Using the spec it is possible to specify a continuous stream by attaching a short term calendar to the interTriggerTimer of a start.
